//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalHospital.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentalHospitalEntities : DbContext
    {
        public DentalHospitalEntities()
            : base("name=DentalHospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment_Table> Appointment_Table { get; set; }
        public virtual DbSet<Contact_Table> Contact_Table { get; set; }
        public virtual DbSet<Doctor_Table> Doctor_Table { get; set; }
        public virtual DbSet<Patient_Details> Patient_Details { get; set; }
        public virtual DbSet<Table_Admin> Table_Admin { get; set; }
    }
}
